# -*- coding: utf-8 -*-
"""parcing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15VSvfHC3kxZjkXoUVrIvsCO53K2cAZxV
"""

import requests
import sys
from bs4 import BeautifulSoup
webpage = requests.get("http://www.1004n.co.kr/content/01intro/09_36.php")
soup = BeautifulSoup(webpage.content, "html.parser")

a=soup.find_all(attrs={'class':'con_tab3'})

sys.stdout = open('output.txt','w')

for x in range(41,60):
    print(soup.select("a")[x].get_text())
